# Generated by Django 3.1.3 on 2020-12-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201211_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mob', models.CharField(max_length=12)),
                ('message', models.TextField()),
                ('tome', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
