# Generated by Django 3.1.3 on 2020-12-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-time',)},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='tome',
            new_name='time',
        ),
    ]
